# Generated by Django 4.1.5 on 2023-08-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0002_textbookarhiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='textbookinvent',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook.textbook', to_field='isbn'),
        ),
    ]
