# Generated by Django 4.1.5 on 2023-08-16 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_alter_textbook_isbn_alter_textbookinvent_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='textbookarhiv',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='textbookinvent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
