# Generated by Django 4.1.5 on 2023-08-21 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_alter_textbook_date_alter_textbookarhiv_date_and_more'),
        ('reader', '0002_reader_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbook.textbookinvent')),
            ],
        ),
    ]
