# Generated by Django 4.1.5 on 2023-06-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBookArhiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.CharField(max_length=10, verbose_name='Инвентарный номер')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Инвентарный номер',
                'verbose_name_plural': 'Инвентарные номера',
            },
        ),
    ]
